# Generated by Django 3.0.1 on 2019-12-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191220_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
